/* ==========================================================================
   POLYSAFE DATASET
   Curated directly from the PolySafe project data document.
   Every record below is transcribed/paraphrased from that source — nothing
   invented. Extend this file as the real dataset grows (see README, Day 3-4).
   ========================================================================== */

// Small helper so each record stays on ~10 readable lines instead of 25+
// kind: "drug-drug" (default) | "drug-disease" | "drug-food" | "drug-drink" | "drug-lab"
// source: "curated" (default, from the project document) | "ai-supplemented" (added by Claude, pending pharmacist review)
function mk(id, drugA, drugB, type, severity, contraindicated, direction, risk, mechanism, effect, monitoring, action, evidence, note, kind, source) {
  return { id, drugA, drugB, type, severity, contraindicated, direction, risk, mechanism, effect, monitoring, action, evidence, note: note || null, kind: kind || "drug-drug", source: source || "curated" };
}

// severity: "critical" | "major" | "moderate" | "minor"
// contraindicated: false | true | "conditional" (string note explains the condition)

const INTERACTIONS = [

  // ---------------- WARFARIN GROUP (11) ----------------
  mk("POLY-WAR-RIF-001","Warfarin","Rifampicin","Pharmacokinetic — enzyme induction","major",false,
    "↓ warfarin effect / ↓ INR",
    "Rifampicin strongly induces warfarin metabolism and can leave the patient inadequately anticoagulated.",
    "Induces CYP2C9, CYP3A4 and other hepatic pathways, increasing warfarin clearance.",
    "Some patients have needed a 5–6× warfarin dose increase to stay therapeutic. The effect builds over time and can persist after rifampicin stops.",
    "INR very closely after starting, during therapy, and again after rifampicin is stopped • watch for thrombosis and, once the dose is raised, for bleeding",
    "Confirm indication and target INR • get a baseline INR • ask whether rifampicin is essential • if so, arrange intensive INR monitoring • never raise warfarin empirically without INR guidance • expect the raised dose to become excessive once rifampicin stops",
    "High/moderate-high — regulatory labeling plus human pharmacokinetic and clinical evidence"),

  mk("POLY-WAR-CBZ-001","Warfarin","Carbamazepine","Pharmacokinetic — enzyme induction","major",false,
    "↓ warfarin effect / ↓ INR",
    "Carbamazepine induces warfarin metabolism and can substantially cut anticoagulant effect, raising thromboembolic risk.",
    "Induction via CYP2C9/CYP3A4; warfarin label explicitly lists carbamazepine as an inducer.",
    "A 166-patient cohort found warfarin dose rose ~49% on average during carbamazepine treatment, with subtherapeutic INR in 79% of patients by week five.",
    "Baseline INR • frequent INR after starting carbamazepine • INR after any carbamazepine dose change • INR after carbamazepine is stopped • watch for signs of thrombosis",
    "Contact prescriber/anticoagulation service • increase INR surveillance • remember the actual dose requirement varies a lot between patients, so don't apply a fixed rule",
    "High/moderate-high — regulatory labeling plus cohort data"),

  mk("POLY-WAR-PHB-001","Warfarin","Phenobarbital","Pharmacokinetic — hepatic enzyme induction","major",false,
    "↓ warfarin effect (generally)",
    "Phenobarbital can induce warfarin metabolism and reduce anticoagulant effect and INR.",
    "Induces CYP2C9/CYP3A4 and other CYP pathways; listed as a CYP2C9 inducer on the warfarin label.",
    "Older data showed reduced anticoagulant response; more recent cohort data found the clearest effect was with carbamazepine, with phenobarbital's independent effect less consistently quantified.",
    "Baseline INR • frequent INR after starting • monitor after dose changes • monitor carefully after discontinuation",
    "Consider an alternative anticonvulsant where clinically appropriate • flag as Major given the consequences of under-anticoagulation, while noting the evidence is less robust than for carbamazepine",
    "Moderate — strong mechanistic support, less consistent direct clinical quantification than carbamazepine"),

  // ---- Fluoroquinolone class, split per-drug (document explicitly instructs this) ----
  mk("POLY-WAR-CIP-001","Warfarin","Ciprofloxacin","Pharmacokinetic/pharmacodynamic — variable","moderate",false,
    "Usually ↑ INR, but variable",
    "Ciprofloxacin can raise warfarin's anticoagulant response and INR, though the size of the effect varies by patient.",
    "Proposed mechanisms: altered gut vitamin-K production, possible CYP effects, the underlying infection itself, reduced oral intake, and protein-binding effects.",
    "A review of 22 publications on fluoroquinolones as a group found inconsistent results — generally small mean INR changes, but some patients had marked elevation and bleeding.",
    "INR before/around starting the antibiotic where feasible • repeat during treatment • repeat after completion when indicated • watch for bleeding symptoms, infection severity and dietary intake",
    "Do NOT treat this as an automatic 'avoid' — treat it as variable and monitor accordingly",
    "Moderate — substantial case-report/observational evidence for the fluoroquinolone class, inconsistent controlled-study findings",
    "Upgrade to Major in patients at high bleeding risk or with a large INR rise."),

  mk("POLY-WAR-LEV-001","Warfarin","Levofloxacin","Pharmacokinetic/pharmacodynamic — variable","moderate",false,
    "Usually ↑ INR, but variable",
    "Levofloxacin can raise warfarin's anticoagulant response and INR — this is the specific fluoroquinolone with the clearest case evidence in the dataset.",
    "Proposed mechanisms: altered gut vitamin-K production, possible CYP effects, the underlying infection itself, reduced oral intake, and protein-binding effects.",
    "Four reported patients receiving levofloxacin experienced INR elevations to 3.5, 8.12 and 11.5, with one experiencing minor bleeding.",
    "INR before/around starting the antibiotic where feasible • repeat during treatment • repeat after completion when indicated • watch for bleeding symptoms, infection severity and dietary intake",
    "Do NOT treat this as an automatic 'avoid' — treat it as variable and monitor accordingly, with extra attention given the documented case reports",
    "Moderate — substantial case-report/observational evidence, inconsistent controlled-study findings",
    "Upgrade to Major in patients at high bleeding risk or with a large INR rise."),

  mk("POLY-WAR-MOX-001","Warfarin","Moxifloxacin","Pharmacokinetic/pharmacodynamic — variable","moderate",false,
    "Usually ↑ INR, but variable",
    "Moxifloxacin can raise warfarin's anticoagulant response and INR, though the size of the effect varies by patient.",
    "Proposed mechanisms: altered gut vitamin-K production, possible CYP effects, the underlying infection itself, reduced oral intake, and protein-binding effects.",
    "As part of the fluoroquinolone class, a review of 22 publications found generally small mean INR changes, but some patients had marked elevation and bleeding.",
    "INR before/around starting the antibiotic where feasible • repeat during treatment • repeat after completion when indicated • watch for bleeding symptoms, infection severity and dietary intake",
    "Do NOT treat this as an automatic 'avoid' — treat it as variable and monitor accordingly",
    "Moderate — substantial case-report/observational evidence for the fluoroquinolone class, inconsistent controlled-study findings",
    "Upgrade to Major in patients at high bleeding risk or with a large INR rise."),

  mk("POLY-WAR-OFL-001","Warfarin","Ofloxacin","Pharmacokinetic/pharmacodynamic — variable","moderate",false,
    "Usually ↑ INR, but variable",
    "Ofloxacin can raise warfarin's anticoagulant response and INR, though the size of the effect varies by patient.",
    "Proposed mechanisms: altered gut vitamin-K production, possible CYP effects, the underlying infection itself, reduced oral intake, and protein-binding effects.",
    "As part of the fluoroquinolone class, a review of 22 publications found generally small mean INR changes, but some patients had marked elevation and bleeding.",
    "INR before/around starting the antibiotic where feasible • repeat during treatment • repeat after completion when indicated • watch for bleeding symptoms, infection severity and dietary intake",
    "Do NOT treat this as an automatic 'avoid' — treat it as variable and monitor accordingly",
    "Moderate — substantial case-report/observational evidence for the fluoroquinolone class, inconsistent controlled-study findings",
    "Upgrade to Major in patients at high bleeding risk or with a large INR rise."),

  mk("POLY-WAR-MTZ-001","Warfarin","Metronidazole","Pharmacokinetic — enzyme inhibition","major",false,
    "↑ warfarin effect / ↑ INR",
    "Metronidazole inhibits metabolism of the more potent S-warfarin enantiomer and can cause excessive anticoagulation and serious bleeding.",
    "CYP2C9 inhibition, listed explicitly on the warfarin label.",
    "A case report described an INR of 8.0 with intracerebral hemorrhage during concomitant use; another study found preemptive dose reduction of ~30–35% prevented significant INR rises in selected patients (not a rule to apply automatically).",
    "INR • bleeding • hemoglobin/hematocrit if bleeding suspected • adherence • other antiplatelets/NSAIDs in use",
    "Consider an alternative antibiotic if clinically appropriate • if metronidazole is essential, increase INR monitoring and coordinate warfarin management — the interaction can matter within a short antibiotic course",
    "High/moderate-high"),

  mk("POLY-WAR-FLC-001","Warfarin","Fluconazole","Pharmacokinetic — enzyme inhibition","major",false,
    "↑ warfarin exposure / ↑ INR",
    "Fluconazole inhibits warfarin metabolism, particularly CYP2C9-mediated S-warfarin clearance, raising anticoagulant exposure and bleeding risk.",
    "CYP2C9 and CYP3A4 inhibition; listed on the current warfarin label.",
    "A human study found fluconazole cut S-warfarin clearance by ~70%. Even a single 150 mg oral dose has caused clinically relevant INR rises in some chronic warfarin patients; the interaction can develop within about a week.",
    "INR before treatment when practical, during therapy, and after treatment when appropriate • bleeding • renal function (fluconazole is substantially renally eliminated)",
    "Applies particularly to systemically absorbed oral/IV fluconazole — a topical antifungal isn't automatically equivalent",
    "High"),

  // ---- Miconazole, split per formulation (document's own table instructs this) ----
  mk("POLY-WAR-MIC-ORAL-001","Warfarin","Miconazole (oral/systemic)","Pharmacokinetic — enzyme inhibition","major",false,
    "↑ anticoagulant effect / ↑ INR",
    "Oral/systemic miconazole can inhibit warfarin metabolism and has been linked to clinically important INR rises and bleeding. The document's own formulation table marks this route 'High concern.'",
    "CYP2C9/CYP3A4 inhibition.",
    "FDA/DailyMed labeling reports bleeding/bruising with concomitant warfarin, with systemic exposure carrying the clearest risk.",
    "Baseline INR where appropriate • close INR monitoring • watch for bruising/bleeding • communicate with the prescriber",
    "Prefer a non-miconazole alternative when reasonable • if concomitant use is necessary, monitor closely",
    "Moderate–High — regulatory labeling documents actual bleeding/bruising reports"),

  mk("POLY-WAR-MIC-BUCCAL-001","Warfarin","Miconazole (buccal/oral mucosal)","Pharmacokinetic — enzyme inhibition","major",false,
    "↑ anticoagulant effect / ↑ INR",
    "Buccal/oral mucosal miconazole can inhibit warfarin metabolism and has been linked to clinically important INR rises and bleeding. The document's own formulation table marks this route 'High concern' — the same as oral/systemic.",
    "CYP2C9/CYP3A4 inhibition, with meaningful mucosal absorption.",
    "FDA labeling for miconazole buccal tablets specifically documents bleeding/bruising with concomitant warfarin.",
    "Baseline INR where appropriate • close INR monitoring • watch for bruising/bleeding • communicate with the prescriber",
    "Prefer a non-miconazole alternative when reasonable • if concomitant use is necessary, monitor closely",
    "Moderate–High — regulatory labeling (miconazole buccal tablet product information) documents this directly"),

  mk("POLY-WAR-MIC-VAG-001","Warfarin","Miconazole (intravaginal)","Pharmacokinetic — enzyme inhibition","moderate",false,
    "↑ anticoagulant effect / ↑ INR (clinically relevant, reported)",
    "Intravaginal miconazole has been associated with a clinically relevant interaction with warfarin, despite lower systemic absorption than oral/buccal use.",
    "Partial systemic absorption allows CYP2C9/CYP3A4 inhibition even via this route.",
    "FDA/DailyMed labeling explicitly includes intravaginal miconazole among formulations with reported bleeding/bruising with concomitant warfarin.",
    "INR monitoring around the treatment course • watch for bruising/bleeding • communicate with the prescriber",
    "Do not assume this route is risk-free just because it's local — the document's own table calls this 'clinically relevant interaction reported,' not negligible",
    "Moderate — regulatory labeling documents reports at this route, though absorption is lower than oral/systemic use"),

  mk("POLY-WAR-MIC-TOP-001","Warfarin","Miconazole (topical)","Pharmacokinetic — enzyme inhibition","moderate",false,
    "Possible ↑ anticoagulant effect / ↑ INR — do not assume negligible",
    "Topical miconazole has been included in reports of bleeding/bruising with concomitant warfarin, so it should not automatically be assumed safe just because it's applied to the skin.",
    "Some systemic absorption is possible depending on the application site, skin condition, and extent of use.",
    "The document's own guidance: 'interaction reported; do not assume negligible risk' for topical use.",
    "Watch for bruising/bleeding if extensive topical use occurs • INR check if any unusual bleeding is noted",
    "Assess how much topical product is being used and over what body surface area before dismissing this as low-risk",
    "Moderate — regulatory labeling includes topical use among reported formulations, though exposure is generally lower than oral/systemic"),

  mk("POLY-WAR-MIC-OTHER-001","Warfarin","Miconazole (other low-absorption topical products)","Pharmacokinetic — enzyme inhibition, formulation-dependent","minor",false,
    "Uncertain / likely low, but assess individually",
    "Other very-low-absorption topical miconazole products (e.g. certain powders or minimal-contact formulations) have not been clearly linked to systemic warfarin interaction, but this depends heavily on the specific product.",
    "Minimal systemic absorption expected, but not guaranteed for every product and every patient.",
    "The document's own instruction here is to assess formulation and exposure individually rather than assign a fixed risk level.",
    "Routine monitoring • reassess if the product or amount used changes",
    "Do not create a blanket 'safe' rule for this category — verify the specific product before treating it as low-risk",
    "Low — insufficient product-specific evidence to assign a firm severity; individual assessment required"),

  mk("POLY-WAR-AMIO-001","Warfarin","Amiodarone","Pharmacokinetic — enzyme inhibition","major",false,
    "↑ warfarin effect / ↑ INR",
    "Amiodarone inhibits warfarin metabolism, potentially causing prolonged, excessive anticoagulation and bleeding.",
    "CYP2C9 and CYP3A4 inhibition, decreasing warfarin clearance; explicitly listed on the warfarin label.",
    "A nationwide cohort saw mean INR rise from 2.6 to 3.1 after amiodarone initiation, with mean warfarin dose falling ~24.6%. Another study found the interaction peaked around 7 weeks, with a mean maximum dose reduction of ~44%.",
    "Baseline INR • frequent INR during early treatment • continued monitoring for several weeks • additional monitoring after amiodarone is stopped or its dose changes",
    "This is not an immediate interaction — amiodarone and its metabolites have long half-lives, so it evolves over weeks. Dose adjustment is often needed but should not follow a fixed universal percentage.",
    "High"),

  mk("POLY-WAR-CLR-001","Warfarin","Clarithromycin","Pharmacokinetic — enzyme inhibition","major",false,
    "↑ anticoagulant effect / ↑ INR",
    "Clarithromycin can enhance warfarin's anticoagulant effect and has been linked to marked INR elevation and bleeding.",
    "CYP3A-mediated metabolism inhibition, plus possible illness-related effects; listed as a CYP3A4 inhibitor on the warfarin label.",
    "Case reports document dramatic INR rises — one reaching 16.8 after a course of clarithromycin, another with severe elevation around five days after starting.",
    "Close INR monitoring • assess other bleeding-risk medicines • monitor clinically for bleeding",
    "Consider whether a non-interacting antibiotic alternative exists before dispensing",
    "Moderate–High — regulatory mechanistic support plus clinically significant case evidence"),

  mk("POLY-WAR-ERY-001","Warfarin","Erythromycin","Pharmacokinetic — enzyme inhibition","major",false,
    "↑ anticoagulant effect",
    "Erythromycin can reduce warfarin clearance and raise anticoagulant response and INR.",
    "CYP-mediated inhibition reducing warfarin clearance; listed as a CYP3A4 inhibitor on the warfarin label.",
    "A pharmacokinetic study found erythromycin reduced warfarin clearance by ~14%; case evidence has reported marked exacerbation of anticoagulant response.",
    "Closer INR monitoring while on erythromycin • watch for bleeding • reassess INR after the antibiotic course ends",
    "Consider antibiotic alternatives where appropriate",
    "Moderate",
    "Treat as Major in a decision-support context when the patient has high baseline bleeding risk or a high therapeutic INR, while keeping the underlying evidence certainty at Moderate."),

  mk("POLY-WAR-CIM-001","Warfarin","Cimetidine","Pharmacokinetic — enzyme inhibition","moderate",false,
    "↑ warfarin exposure",
    "Cimetidine can inhibit warfarin metabolism and raise exposure, though the clinical effect is usually smaller and more variable than with stronger inhibitors like amiodarone or fluconazole.",
    "Inhibition of hepatic metabolism, particularly demonstrated for R-warfarin.",
    "A steady-state study found a 28% rise in R-warfarin trough concentration and a 23% reduction in R-warfarin clearance, but no significant overall effect on PT/factor VII in healthy volunteers — likely minimal clinical significance for most patients.",
    "Monitor INR, especially around starting/stopping cimetidine • consider patient-specific bleeding risk",
    "If acid suppression is needed, the prescriber may consider an alternative H2 antagonist depending on the clinical indication",
    "Moderate",
    "Do not place in the same risk category as rifampicin, metronidazole, fluconazole or amiodarone."),

  // ---------------- ASPIRIN GROUP (16) ----------------
  mk("PS-ASA-WAR-001","Aspirin","Warfarin","Pharmacodynamic (PK effects possible but not principal)","major",false,
    "Additive bleeding risk",
    "Aspirin adds antiplatelet and gastrointestinal bleeding effects to warfarin's anticoagulation, raising the risk of clinically significant bleeding.",
    "Aspirin irreversibly inhibits platelet COX-1 (impairing primary hemostasis) while warfarin lowers vitamin-K-dependent clotting factors (impairing secondary hemostasis) — plus aspirin causes gastric mucosal injury.",
    "INR may stay unchanged even as bleeding risk rises, because this is an effect-based interaction, not a concentration-based one. High-risk patients: supratherapeutic INR, prior GI ulcer/bleeding, elderly/frail, renal or hepatic impairment, high-dose aspirin, high-intensity warfarin, concurrent NSAIDs/steroids/SSRIs, heavy alcohol use.",
    "INR • CBC/hemoglobin • stool/clinical bleeding checks • renal function • exam for bruising/hematoma — individualize frequency rather than using a fixed interval",
    "Continue with monitoring when the combination is intentional and benefits outweigh risk • contact prescriber if aspirin has no clear indication, bleeding occurs, INR is excessive, or other bleeding-risk drugs are stacked",
    "High — regulatory labeling and clinical/guideline evidence"),

  mk("PS-ASA-API-001","Aspirin","Apixaban","Pharmacodynamic","major",false,
    "Additive antiplatelet + anticoagulant effect",
    "Aspirin adds antiplatelet activity to apixaban's anticoagulation, increasing major bleeding risk.",
    "Aspirin blocks platelet COX-1; apixaban blocks factor Xa — impaired platelet plug formation plus impaired thrombin generation.",
    "In ARISTOTLE, bleeding rose from 1.8%/year without aspirin to 3.4%/year with it. No clinically important PK interaction (apixaban exposure) has been established — this is a PD interaction.",
    "CBC • hemoglobin/hematocrit • renal function • hepatic function when relevant • clinical bleeding • medication reconciliation. Routine INR monitoring is NOT a valid measure of apixaban effect.",
    "Continue with monitoring if aspirin has a strong indication (e.g. appropriate coronary indication) • recommend deprescribing/reassessment if aspirin lacks a clear indication",
    "High"),

  mk("PS-ASA-RIV-001","Aspirin","Rivaroxaban","Pharmacodynamic","major",false,
    "Additive antiplatelet + anticoagulant effect",
    "Aspirin adds antiplatelet activity to rivaroxaban and increases bleeding risk, without meaningfully changing rivaroxaban blood levels.",
    "Aspirin inhibits platelet aggregation; rivaroxaban inhibits factor Xa — additive impairment of hemostasis.",
    "Concomitant aspirin was an independent risk factor for major bleeding in ROCKET-AF; aspirin did not alter rivaroxaban pharmacokinetics — this is effect-based, not exposure-based.",
    "CBC • hemoglobin • renal function • clinical bleeding • GI symptoms • hematuria • neurologic symptoms",
    "Continue with monitoring when aspirin is specifically indicated • recommend reassessment when it's unnecessary",
    "High"),

  mk("PS-ASA-HEP-001","Aspirin","Heparin","Pharmacodynamic","major",false,
    "Additive impairment of hemostasis",
    "Aspirin and heparin impair different components of hemostasis (platelets vs. coagulation factors), producing additive bleeding risk.",
    "Aspirin inhibits platelet aggregation; heparin potentiates antithrombin, inhibiting thrombin and/or factor Xa depending on the heparin type.",
    "This combination is intentionally used in several cardiovascular/thrombotic settings — it isn't inherently wrong, just higher risk.",
    "Unfractionated heparin: aPTT or validated anti-Xa per protocol, CBC, platelet count, hemoglobin, clinical bleeding. LMWH: anti-Xa reserved for selected situations, not routine.",
    "Continue with monitoring when intentionally prescribed • contact prescriber if bleeding, excessive anticoagulation, thrombocytopenia, or an unnecessary duplicate antithrombotic regimen shows up",
    "High pharmacodynamic evidence"),

  mk("PS-ASA-CLO-001","Aspirin","Clopidogrel","Pharmacodynamic / deliberate combination therapy","major",false,
    "Additive platelet inhibition",
    "Aspirin and clopidogrel produce additive platelet inhibition, raising bleeding risk — but this combination (dual antiplatelet therapy / DAPT) is often deliberately prescribed in ACS/PCI and other high-risk cardiovascular settings.",
    "Aspirin blocks COX-1 (↓ thromboxane A2); clopidogrel blocks the P2Y12 receptor (↓ ADP-mediated activation) — complementary platelet inhibition.",
    "Current ACS guidance recognizes aspirin + a P2Y12 inhibitor as standard treatment in appropriate patients, alongside bleeding-risk reduction strategies.",
    "CBC • hemoglobin • bleeding symptoms • GI symptoms • medication duration/indication • any upcoming procedures",
    "Continue with monitoring when DAPT is clinically indicated • contact prescriber if duration looks excessive, bleeding risk is high, or the original indication has expired",
    "High",
    "Not inherently inappropriate — flag for duration/indication review, not automatic avoidance."),

  mk("PS-ASA-IBU-001","Aspirin","Ibuprofen","Pharmacodynamic + GI toxicity + antiplatelet antagonism","moderate",false,
    "↑ GI bleeding risk; possible ↓ aspirin cardioprotection",
    "Ibuprofen can add GI mucosal injury on top of aspirin's, and can competitively block aspirin's irreversible COX-1 platelet effect if timed wrong.",
    "Additive GI toxicity, plus ibuprofen competing with aspirin at the platelet COX-1 site.",
    "FDA data (for IR low-dose aspirin 81 mg + ibuprofen 400 mg) indicate taking ibuprofen at least 8 hours before aspirin, or at least 30 minutes after, can minimize the interaction under the studied conditions. This timing evidence is mainly for immediate-release low-dose aspirin — enteric-coated/modified-release products may behave differently, so don't apply the rule universally.",
    "GI symptoms • bleeding signs • confirm whether aspirin is cardioprotective (low-dose) vs anti-inflammatory (high-dose)",
    "Avoid chronic ibuprofen alongside cardioprotective aspirin if alternatives exist • if occasional ibuprofen is needed, address timing and indication • consider acetaminophen where appropriate",
    "High for the mechanism; FDA explicitly notes the two can sometimes be used together with professional guidance on timing",
    "Escalate to Major in high-risk patients (e.g. those relying on aspirin's cardioprotection)."),

  mk("PS-ASA-PRED-001","Aspirin","Prednisolone","Pharmacodynamic + pharmacokinetic","moderate",false,
    "Additive GI toxicity; altered salicylate clearance",
    "Prednisolone and aspirin can produce additive GI toxicity and bleeding, while corticosteroid-related changes in salicylate clearance may alter aspirin exposure.",
    "Additive GI adverse effects; corticosteroids can increase salicylate clearance, and withdrawing the steroid can then raise the risk of salicylate toxicity in susceptible patients.",
    "Risk: dyspepsia, gastritis, peptic ulcer, GI bleeding, and salicylate toxicity after steroid withdrawal in selected chronic/high-dose aspirin patients.",
    "Continue with monitoring when clinically necessary • consider gastroprotection based on the patient's GI risk",
    "Watch specifically around corticosteroid dose reduction/withdrawal for signs of salicylate toxicity in chronic high-dose aspirin users",
    "Moderate-to-high"),

  mk("PS-ASA-DEX-001","Aspirin","Dexamethasone","Pharmacodynamic + pharmacokinetic","moderate",false,
    "Additive GI toxicity; altered salicylate clearance",
    "Dexamethasone can increase aspirin-related GI toxicity and may increase salicylate clearance, changing salicylate exposure.",
    "Additive GI mucosal vulnerability; dexamethasone can increase salicylate clearance.",
    "Labeling specifically states aspirin plus corticosteroids increases GI adverse effects.",
    "GI symptoms • occult/overt bleeding • CBC if prolonged/high-risk • watch for salicylate toxicity if the steroid is withdrawn • renal function when appropriate",
    "Continue with monitoring if clinically necessary",
    "Moderate-to-high"),

  mk("PS-ASA-SER-001","Aspirin","Sertraline","Pharmacodynamic","moderate",false,
    "Additive impairment of primary hemostasis",
    "Sertraline can impair platelet-mediated hemostasis, and combined use with aspirin may increase bleeding risk.",
    "Sertraline inhibits serotonin reuptake into platelets, reducing platelet serotonin and impairing aggregation; aspirin adds COX-1 platelet inhibition.",
    "Sertraline labeling explicitly warns SSRIs/SNRIs can increase bleeding, and that concomitant aspirin, NSAIDs, warfarin or other anticoagulants can add to that risk. No established PK interaction raising sertraline concentration.",
    "Bruising • epistaxis • GI bleeding • CBC when indicated • check for other anticoagulants/antiplatelets",
    "Continue with monitoring when both are clinically indicated • avoid unnecessary aspirin/NSAID exposure",
    "Moderate-to-high"),

  mk("PS-ASA-FLX-001","Aspirin","Fluoxetine","Pharmacodynamic","moderate",false,
    "Additive impairment of platelet aggregation",
    "Fluoxetine can increase bleeding susceptibility through platelet serotonin effects, additive with aspirin's antiplatelet activity.",
    "Reduced platelet serotonin uptake (fluoxetine) plus irreversible COX-1 inhibition (aspirin).",
    "Fluoxetine labeling identifies abnormal bleeding with SSRIs and specifically warns that aspirin and other coagulation-affecting drugs add to the risk. Fluoxetine and its active metabolite have long half-lives, so the effect may not disappear quickly after stopping.",
    "Bleeding symptoms as above • note the long washout period when the drug is discontinued",
    "Continue with monitoring when clinically necessary",
    "Moderate-to-high"),

  mk("PS-ASA-FUR-001","Aspirin","Furosemide","Pharmacodynamic / renal","moderate",false,
    "↓ diuretic response; renal risk",
    "Higher-dose aspirin may reduce furosemide's diuretic effect and increase renal risk, particularly in volume-depleted or renal-impaired patients.",
    "High-dose aspirin/NSAID effect inhibits renal prostaglandin synthesis, reducing renal vasodilatory support and natriuretic/diuretic response.",
    "Low-dose antiplatelet aspirin is NOT equivalent to high-dose anti-inflammatory aspirin for this interaction — dose matters.",
    "Serum creatinine/eGFR • urine output • weight/edema • blood pressure • electrolytes • volume status • diuretic response",
    "Check the aspirin dose/indication before flagging this as clinically significant",
    "Moderate"),

  mk("PS-ASA-HCT-001","Aspirin","Hydrochlorothiazide","Pharmacodynamic / renal","moderate",false,
    "↓ diuretic/antihypertensive response; renal risk",
    "Higher-dose aspirin may reduce hydrochlorothiazide's diuretic/antihypertensive effect and increase renal risk.",
    "Renal prostaglandin inhibition at anti-inflammatory/salicylate doses alters renal hemodynamics, reducing natriuresis/diuresis.",
    "Labeling recommends close observation of diuretic efficacy when thiazides are combined with NSAIDs.",
    "Blood pressure • weight/edema • serum creatinine/eGFR • sodium • potassium • volume status",
    "Primarily relevant at higher aspirin/salicylate exposure — check the dose",
    "Moderate"),

  mk("PS-ASA-LIS-001","Aspirin","Lisinopril","Pharmacodynamic / renal","moderate",false,
    "↓ antihypertensive effect; renal risk",
    "Higher-dose aspirin may reduce lisinopril's antihypertensive effect and increase renal impairment risk, especially in susceptible patients.",
    "Aspirin/NSAID lowers renal prostaglandins while lisinopril lowers angiotensin-II-mediated efferent arteriolar tone — combined, this reduces renal autoregulatory reserve.",
    "Labeling states NSAIDs may cause renal deterioration, including acute renal failure, particularly in elderly, volume-depleted or renally impaired patients.",
    "Serum creatinine/eGFR • potassium • blood pressure • volume status • urine output where appropriate",
    "Interaction is most relevant to anti-inflammatory-dose aspirin/NSAID use, not low-dose antiplatelet aspirin",
    "Moderate"),

  mk("PS-ASA-ENA-001","Aspirin","Enalapril","Pharmacodynamic / renal","moderate",false,
    "↓ antihypertensive effect; renal risk",
    "Higher-dose aspirin may blunt enalapril's antihypertensive effect and raise renal impairment risk in susceptible patients.",
    "Same afferent/efferent arteriolar mechanism as with lisinopril — reduced renal autoregulatory capacity when combined.",
    "Labeling warns of possible renal deterioration, including acute renal failure, particularly in elderly, volume-depleted or renally impaired patients.",
    "Creatinine/eGFR • potassium • blood pressure • hydration • diuretic use • clinical renal status",
    "Same dose-dependence as other ACE-inhibitor + aspirin/NSAID pairs",
    "Moderate"),

  mk("PS-ASA-LOS-001","Aspirin","Losartan","Pharmacodynamic / renal","moderate",false,
    "↓ antihypertensive effect; renal risk",
    "Higher-dose aspirin may blunt losartan's antihypertensive effect and increase renal impairment risk, particularly in elderly, volume-depleted or renal-impaired patients.",
    "Renal prostaglandin inhibition combined with AT1 receptor blockade reduces renal compensatory mechanisms.",
    "Risk is particularly important in the 'triple whammy' combination: ARB + diuretic + NSAID/aspirin, due to volume depletion plus altered renal regulation.",
    "Creatinine/eGFR • potassium • blood pressure • volume status • diuretic response",
    "Flag especially when a diuretic is also on the medication list",
    "Moderate-to-high"),

  mk("PS-ASA-TEL-001","Aspirin","Telmisartan","Pharmacodynamic / renal","moderate",false,
    "↓ antihypertensive effect; renal risk",
    "Higher-dose aspirin may reduce telmisartan's antihypertensive effect and increase renal impairment risk in susceptible patients.",
    "Renal prostaglandin inhibition combined with AT1 blockade impairs renal autoregulation.",
    "Same class-level mechanism as losartan.",
    "Serum creatinine/eGFR • potassium • blood pressure • volume status • edema/weight where appropriate",
    "Check for concurrent diuretic use (triple-whammy risk)",
    "Moderate-to-high"),

  // ---------------- CEFTRIAXONE GROUP (5) ----------------
  mk("PS-CRO-RL-001","Ceftriaxone","Lactated Ringer's Solution","Physical/chemical IV incompatibility","critical","conditional",
    "Precipitation, not a metabolic interaction",
    "Ceftriaxone can bind calcium in Lactated Ringer's to form an insoluble ceftriaxone-calcium precipitate — potentially fatal in neonates.",
    "Calcium in Lactated Ringer's reacts with ceftriaxone → insoluble precipitate → potential intravascular deposition in lungs/kidneys.",
    "Official Lactated Ringer's labeling warns against simultaneous administration with ceftriaxone in neonates, describing fatal precipitation in the lungs and kidneys.",
    "IV line compatibility • administration sequence • patient age • signs of acute respiratory compromise • renal function when indicated • infusion-site/line abnormalities",
    "Neonates ≤28 days: do NOT administer concomitantly, even via separate lines — contact prescriber/IV therapy team for an alternative. Patients >28 days: sequential administration only, with thorough line flushing using a compatible fluid.",
    "High — regulatory/product labeling",
    "Contraindicated specifically in neonates ≤28 days receiving IV ceftriaxone with IV calcium-containing solutions. For older patients, this becomes a procedural precaution, not a contraindication."),

  mk("PS-CRO-WAR-001","Ceftriaxone","Warfarin","Pharmacodynamic/indirect","major",false,
    "↑ anticoagulant effect / ↑ INR",
    "Ceftriaxone may enhance anticoagulant effect and raise INR, potentially causing clinically significant bleeding.",
    "Likely linked to reduced vitamin-K availability/coagulation physiology, worsened by low vitamin-K reserve during infection and antibiotic therapy.",
    "A retrospective study found ceftriaxone produced a significantly greater INR rise than comparator antibiotics in chronic warfarin patients treated for UTI. A case report described INR rising to 10.74 and later 16.99 after ceftriaxone injections.",
    "INR/PT • clinical bleeding • consider hemoglobin/hematocrit and occult blood when indicated",
    "Do not automatically stop warfarin — check baseline INR, increase surveillance, assess bleeding, review other bleeding-risk drugs, and communicate significant INR changes to the prescriber/anticoagulation service",
    "Moderate-to-high — labeling plus clinical studies/case reports"),

  mk("PS-CRO-ETOH-001","Ceftriaxone","Alcohol/Ethanol","Possible pharmacodynamic/toxicodynamic","moderate",false,
    "Possible disulfiram-like reaction",
    "A rare disulfiram-like alcohol intolerance has been reported with ceftriaxone, though the evidence is limited and conflicting.",
    "Proposed: interference with ethanol metabolism → possible acetaldehyde accumulation → flushing, nausea, vomiting, tachycardia, and in severe reactions, hypotension. This mechanism is uncertain/proposed, not established, for ceftriaxone specifically.",
    "Severe reactions appear rare; possible symptoms include facial flushing, headache, nausea, vomiting, palpitations, sweating, hypotension, chest discomfort.",
    "Clinical symptoms during any alcohol exposure while on ceftriaxone",
    "Recommend avoiding alcohol during treatment as a precaution, but do NOT label this 'contraindicated' — the evidence doesn't support that strength of claim",
    "Low / conflicting",
    "A good example of why PolySafe needs an honest evidence-quality field rather than forcing every finding into a confident category."),

  mk("PS-CRO-GENT-001","Ceftriaxone","Gentamicin","Therapeutic synergism + IV admixture incompatibility","moderate",false,
    "Intentional synergy, with a mixing caveat",
    "The combination can provide useful antibacterial synergy against some Gram-negative organisms, but requires attention to gentamicin toxicity and how the two drugs are administered.",
    "Ceftriaxone weakens the bacterial cell wall, improving gentamicin's access to its ribosomal target — a therapeutic interaction, not an adverse one.",
    "Gentamicin labeling notes synergism with cephalosporins against some Gram-negative organisms. Separately, ceftriaxone labeling states aminoglycosides are incompatible with ceftriaxone in the same IV admixture.",
    "Serum creatinine • eGFR/renal function • urine output • gentamicin levels when TDM is indicated • hearing/vestibular symptoms where relevant",
    "Confirm indication and gentamicin dosing • assess renal function • do NOT mix the two drugs in the same IV admixture — use sequential administration with proper line flushing",
    "Supported by official gentamicin/ceftriaxone labeling",
    "'Can be used together clinically' does not mean 'can be mixed in the same IV bag.' Keep those as two separate facts in the record."),

  mk("PS-CRO-CAOH-001","Ceftriaxone","Calcium Hydroxide (oral)","No clinically significant interaction established","minor",false,
    "None established for the oral route",
    "There is no well-established clinically significant interaction between ceftriaxone and oral calcium hydroxide, unlike the serious interaction with IV calcium-containing solutions.",
    "The dangerous ceftriaxone-calcium interaction involves parenteral calcium exposure specifically, not the presence of calcium in an oral product. Ceftriaxone labeling reports no interaction with oral calcium-containing products or IM ceftriaxone with calcium products.",
    "No special clinical effect established.",
    "Routine clinical monitoring only",
    "Do not flag this as a severe alert — that would be a false positive generated by confusing 'calcium the element' with 'IV calcium-containing solution'",
    "Labeling-supported",
    "Deliberately included as a negative/no-interaction record. This exact case — same element, different route, completely different risk — is the reason PolySafe needs route/formulation-aware logic instead of a flat drug-name match."),

  // ---------------- CLARITHROMYCIN / ERYTHROMYCIN GROUP (16) ----------------
  mk("PS-CLR-SIM-001","Clarithromycin","Simvastatin","Pharmacokinetic — CYP3A4 inhibition","critical",true,
    "↑ simvastatin exposure",
    "Strong CYP3A4 inhibition can markedly raise simvastatin exposure and cause severe myopathy/rhabdomyolysis.",
    "Clarithromycin strongly inhibits CYP3A4, simvastatin's major metabolic pathway, sharply increasing plasma exposure.",
    "Risk includes myalgia, myopathy, marked CK elevation, rhabdomyolysis, and acute kidney injury from myoglobinuria. Watch for unexplained muscle pain/tenderness/weakness, dark urine, reduced urine output, severe fatigue.",
    "If exposure already occurred: CK if symptomatic, serum creatinine, renal function, urinalysis/myoglobin when indicated. Routine CK monitoring isn't required for a brief asymptomatic exposure.",
    "Do not dispense the combination without intervention • contact the prescriber • recommend an alternative antibiotic, or temporary interruption of simvastatin, depending on the clinical situation • dose separation does NOT fix this (it's metabolic, not absorption-based)",
    "High — regulatory labeling plus established pharmacology",
    "Simvastatin labeling specifically names clarithromycin among contraindicated strong CYP3A4 inhibitors."),

  mk("PS-CLR-LOV-001","Clarithromycin","Lovastatin","Pharmacokinetic — CYP3A4 inhibition","critical",true,
    "↑ lovastatin exposure",
    "Clarithromycin strongly inhibits CYP3A4 and can markedly increase lovastatin exposure, causing potentially life-threatening rhabdomyolysis.",
    "CYP3A4 inhibition decreases lovastatin metabolism, sharply raising exposure.",
    "Same myopathy/rhabdomyolysis/AKI risk profile as clarithromycin + simvastatin.",
    "If inadvertent exposure occurs: muscle symptoms, CK if symptomatic, renal function, urine appearance/output",
    "Do not approve concurrent therapy • recommend an alternative antibiotic or appropriate temporary statin management • dose separation does not help",
    "High — regulatory labeling plus well-established CYP3A4 mechanism"),

  mk("PS-ERY-SIM-001","Erythromycin","Simvastatin","Pharmacokinetic — CYP3A4 inhibition","critical",true,
    "↑ simvastatin exposure",
    "Erythromycin can substantially increase simvastatin exposure and the risk of myopathy/rhabdomyolysis.",
    "CYP3A4 inhibition reduces simvastatin metabolism, increasing systemic exposure.",
    "Myalgia, myopathy, rhabdomyolysis, acute kidney injury.",
    "If inadvertent coadministration occurs: muscle symptoms, CK if symptomatic, renal function",
    "Avoid the combination • consider an alternative antibiotic or alternative lipid-lowering strategy • dose separation is not reliable",
    "High",
    "Erythromycin labeling specifically warns against concomitant use with lovastatin or simvastatin."),

  mk("PS-ERY-LOV-001","Erythromycin","Lovastatin","Pharmacokinetic — CYP3A4 inhibition","critical",true,
    "↑ lovastatin exposure",
    "Erythromycin + lovastatin can cause excessive statin exposure and severe muscle toxicity.",
    "CYP3A4 inhibition reduces lovastatin metabolism, raising exposure and muscle toxicity risk.",
    "Myopathy, rhabdomyolysis, acute kidney injury.",
    "Muscle pain/weakness • CK when indicated • creatinine/renal function • urine changes",
    "Avoid combination • recommend an alternative antibiotic or lipid-lowering approach",
    "High"),

  mk("PS-CLR-WAR-001","Clarithromycin","Warfarin","Pharmacokinetic + clinical","major",false,
    "↑ anticoagulant effect / ↑ INR",
    "Clarithromycin can increase warfarin's anticoagulant effect, causing significant INR elevation and potentially serious bleeding.",
    "Multiple possible contributors: inhibition of warfarin metabolism, changes in gut flora/vitamin K availability, acute infection/inflammation, reduced dietary vitamin K during illness, and individual warfarin sensitivity — not a single clean CYP pathway.",
    "One case report documented an INR of 16.8; an observational study found increased serious bleeding risk among warfarin users given clarithromycin.",
    "INR/PT more frequently during and after starting the antibiotic • watch for bleeding symptoms",
    "Determine indication for clarithromycin, check current INR, assess bleeding risk, review other antithrombotics, consider an alternative antibiotic • notify prescriber • don't reduce warfarin dose automatically without INR/clinical context",
    "High — labeling, case reports and observational evidence"),

  mk("PS-ERY-WAR-001","Erythromycin","Warfarin","Pharmacokinetic + clinical","major",false,
    "↑ anticoagulant effect / ↑ INR",
    "Erythromycin can increase anticoagulant response to warfarin, particularly important in elderly patients.",
    "Inhibition of warfarin metabolism plus other illness-related factors.",
    "Increased INR, anticoagulant effect and bleeding risk (bruising, epistaxis, hematuria, GI bleeding, serious hemorrhage).",
    "INR • PT • bleeding symptoms, with attention to age, renal/hepatic function and other interacting medications",
    "Increase INR monitoring during and after erythromycin • don't let the patient change warfarin dose independently",
    "High — regulatory labeling and clinical experience"),

  mk("PS-CLR-API-001","Clarithromycin","Apixaban","Pharmacokinetic — CYP3A4/P-gp inhibition","major",false,
    "↑ apixaban exposure",
    "Clarithromycin increases apixaban exposure through CYP3A4/P-gp inhibition — but current U.S. labeling states no apixaban dose adjustment is needed solely for this combination.",
    "Apixaban is a CYP3A4 and P-gp substrate; clarithromycin inhibits both. A PK study found Cmax ↑ ~30% and AUC ↑ ~60%.",
    "Potentially increased minor, major, GI or intracranial bleeding, especially in the elderly, renally impaired, low body weight, or those on other antithrombotics/NSAIDs.",
    "No routine INR monitoring applies to apixaban. Monitor bleeding, hemoglobin/hematocrit when indicated, renal and hepatic function, other bleeding-risk meds.",
    "Do not automatically label this contraindicated — review bleeding risk, confirm renal function and current apixaban dose, review concomitant antiplatelets/NSAIDs, and consider an alternative antibiotic only in very high-risk patients",
    "Regulatory PK study data",
    "Important negative case: don't apply the blanket rule 'strong CYP3A4 inhibitor + CYP3A4 substrate = contraindicated' — the label itself says no dose change is needed here."),

  mk("PS-CLR-RIV-001","Clarithromycin","Rivaroxaban","Pharmacokinetic — CYP3A4/P-gp inhibition","moderate",false,
    "↑ rivaroxaban exposure (not clinically restricted per label)",
    "Clarithromycin inhibits CYP3A4/P-gp and can increase rivaroxaban exposure, but current U.S. labeling states no special precautions are necessary solely because of clarithromycin.",
    "Rivaroxaban is metabolized/transported via CYP3A4/5, P-gp and BCRP; clarithromycin inhibits CYP3A4 and P-gp.",
    "Potential increase in bleeding risk, particularly with additional risk factors present.",
    "Bleeding • renal function • hemoglobin when indicated • concomitant antithrombotics/NSAIDs",
    "Do not automatically recommend avoiding rivaroxaban solely because clarithromycin is present — assess the whole clinical picture",
    "Product labeling",
    "Another explicit label-based exception to the generic CYP3A4-inhibitor rule."),

  mk("PS-ERY-API-001","Erythromycin","Apixaban","Pharmacokinetic — CYP3A/P-gp inhibition","moderate",false,
    "↑ apixaban exposure",
    "Erythromycin may increase apixaban exposure through CYP3A/P-gp inhibition.",
    "Apixaban is a CYP3A and P-gp substrate; erythromycin inhibits both pathways.",
    "Evidence reviews estimate an exposure increase in roughly the range seen with clarithromycin, though direct regulatory evidence is less definitive.",
    "Bleeding • CBC/hemoglobin when indicated • renal function • hepatic function when relevant",
    "Assess renal function, apixaban dose, bleeding history and concomitant antithrombotic therapy • consider an alternative antibiotic in high-risk patients",
    "Moderate — mechanistically strong, less direct clinical evidence than for clarithromycin"),

  mk("PS-ERY-RIV-001","Erythromycin","Rivaroxaban","Pharmacokinetic — CYP3A/P-gp inhibition, renal-dependent","major","conditional",
    "↑ rivaroxaban exposure, magnified by renal impairment",
    "Erythromycin can substantially increase rivaroxaban exposure, particularly when renal function is impaired.",
    "Erythromycin inhibits P-gp and CYP3A; rivaroxaban is a substrate of both, and reduced renal clearance magnifies the effect.",
    "With erythromycin: mild renal impairment → rivaroxaban AUC ↑ ~76%; moderate renal impairment → AUC ↑ ~99% (Cmax ↑ ~56% and ~64% respectively).",
    "Bleeding • renal function • hemoglobin • concomitant antithrombotics",
    "Calculate/verify CrCl before approving. Current labeling states rivaroxaban should not be used with erythromycin in patients with CrCl 15 to <80 mL/min unless benefit clearly justifies the risk — this is the single most important check for this pair.",
    "Regulatory PK study data",
    "CrCl 15–<80 mL/min = restricted per label. Normal renal function = lower but still real risk. This is the clearest example in the dataset of a context-dependent (not fixed) severity."),

  mk("PS-CLR-CBZ-001","Clarithromycin","Carbamazepine","Pharmacokinetic — CYP3A4 inhibition","major",false,
    "↑ carbamazepine concentration",
    "Clarithromycin inhibits carbamazepine metabolism and can produce toxic carbamazepine concentrations.",
    "CYP3A4 inhibition reduces carbamazepine clearance; the clarithromycin label reports increased carbamazepine concentrations with concomitant use.",
    "CNS toxicity: dizziness, diplopia, ataxia, nystagmus, somnolence, confusion, nausea/vomiting, dysarthria; hyponatremia can also become relevant.",
    "Carbamazepine serum concentration • neurological status • sodium • liver function when indicated",
    "Prefer an alternative antibiotic when appropriate • if unavoidable, discuss with the prescriber and consider level monitoring • dose separation does not correct CYP3A4 inhibition",
    "High — regulatory labeling plus pharmacokinetic evidence"),

  mk("PS-ERY-CBZ-001","Erythromycin","Carbamazepine","Pharmacokinetic — CYP3A inhibition","major",false,
    "↑ carbamazepine concentration",
    "Erythromycin can substantially increase carbamazepine concentrations and cause CNS toxicity.",
    "CYP3A-mediated inhibition reduces carbamazepine clearance; case reports describe concentrations rising roughly two- to three-fold after starting erythromycin.",
    "CNS toxicity: ataxia, diplopia, nystagmus, drowsiness, confusion, nausea/vomiting, hyponatremia.",
    "Carbamazepine level • neurological status • sodium • liver function when appropriate",
    "Recommend an alternative antibiotic where appropriate • if unavoidable, monitor closely and consider a serum level check • educate the patient on toxicity symptoms",
    "High — clinical PK studies, case reports, established mechanism"),

  mk("PS-CLR-COL-001","Clarithromycin","Colchicine","Pharmacokinetic — CYP3A4/P-gp inhibition","critical","conditional",
    "Marked colchicine accumulation",
    "Clarithromycin can markedly increase colchicine exposure and cause fatal colchicine toxicity.",
    "Clarithromycin inhibits both CYP3A4 and P-gp; colchicine is a substrate of both, so metabolism and transport are both reduced, causing marked accumulation.",
    "Early: diarrhea, vomiting, abdominal pain, nausea. Progressive: myopathy, neuropathy, rhabdomyolysis, bone marrow suppression, pancytopenia, hepatotoxicity, multiorgan failure, death.",
    "GI symptoms • CBC • CK if muscle symptoms occur • renal function • hepatic function • neuromuscular symptoms",
    "Renal or hepatic impairment: do NOT dispense without urgent prescriber intervention. Normal renal/hepatic function: still high risk — generally avoid if an effective alternative antibiotic exists. Dose separation does not help — inhibition is systemic.",
    "High — regulatory labeling plus serious/fatal clinical reports",
    "Colchicine labeling specifically contraindicates strong CYP3A4/P-gp inhibitors like clarithromycin in patients with renal or hepatic impairment."),

  mk("PS-ERY-COL-001","Erythromycin","Colchicine","Pharmacokinetic — CYP3A4/P-gp inhibition","major","conditional",
    "↑ colchicine exposure",
    "Erythromycin can increase colchicine exposure and cause potentially serious or fatal colchicine toxicity, with risk rising sharply in renal or hepatic impairment.",
    "Erythromycin inhibits CYP3A4 and affects P-gp-mediated transport; colchicine depends on both for clearance.",
    "Severe diarrhea, vomiting, abdominal pain, myopathy, neuropathy, rhabdomyolysis, bone marrow suppression, hepatotoxicity, multiorgan toxicity.",
    "GI symptoms • CBC • CK • renal function • liver function • neuromuscular symptoms",
    "Choose another antibiotic if clinically possible • if unavoidable, apply the dose reduction from current colchicine labeling and monitor closely • dose separation is not reliable",
    "High–Moderate — strong pharmacologic rationale and regulatory labeling",
    "No blanket regulatory contraindication from the erythromycin label alone, but risk is substantially greater with renal or hepatic impairment."),

  mk("PS-CLR-DIG-001","Clarithromycin","Digoxin","Pharmacokinetic — P-gp inhibition","major",false,
    "↑ digoxin exposure",
    "Clarithromycin can increase digoxin exposure and the risk of potentially serious digoxin toxicity and arrhythmias.",
    "Digoxin is a P-glycoprotein substrate; clarithromycin inhibits P-gp, altering digoxin transport and elimination.",
    "GI: nausea, vomiting, anorexia, abdominal discomfort. Neuro/visual: confusion, weakness, visual disturbances. Cardiac: bradycardia, AV block, arrhythmias — potentially life-threatening.",
    "Serum digoxin concentration (timed correctly relative to last dose) • heart rate • ECG when indicated • renal function • potassium • magnesium",
    "Check renal function, digoxin dose, prior digoxin level, and potassium/magnesium before dispensing • consider an alternative antibiotic where appropriate",
    "High — regulatory labeling, clinical reports, pharmacologic evidence"),

  mk("PS-ERY-DIG-001","Erythromycin","Digoxin","P-gp-related, variable","moderate",false,
    "Possible ↑ digoxin exposure",
    "Erythromycin may increase digoxin exposure and toxicity risk, though the clinical magnitude varies between patients and studies.",
    "Possible P-gp-mediated interference with digoxin handling.",
    "Nausea, vomiting, anorexia, fatigue, confusion, visual changes, bradycardia, AV block, arrhythmias.",
    "Digoxin concentration when clinically indicated • heart rate • ECG if symptomatic/high risk • renal function • potassium • magnesium",
    "Consider an alternative antibiotic in high-risk patients • otherwise assess digoxin level and monitor for toxicity, especially in the elderly or renally impaired",
    "Moderate–High",
    "Upgrade toward Major in elderly or renally impaired patients."),

  // ---------------- NEW CATEGORY: DRUG–DISEASE (2) ----------------
  mk("PS-DIS-PROP-BRADY-001","Propranolol","Bradycardia","Drug–Disease Interaction","critical",true,
    "Worsening of pre-existing bradycardia",
    "Propranolol is a non-selective beta-blocker that slows heart rate further and can worsen clinically significant pre-existing bradycardia or other important bradyarrhythmias where labeling identifies this as a contraindication.",
    "Blocks cardiac β1-adrenergic receptors, reducing sympathetic stimulation of the sinoatrial node and further slowing heart rate; may also impair cardiac conduction.",
    "Further reduction in heart rate, symptomatic bradycardia, hypotension, dizziness or syncope, worsening conduction abnormalities, and in severe cases clinically significant cardiac compromise. Particular caution with sinus bradycardia, existing conduction abnormalities, sick sinus syndrome, or 2nd/3rd-degree AV block without a pacemaker.",
    "Heart rate • blood pressure • symptoms of bradycardia • dizziness or syncope • signs of impaired cardiac conduction",
    "Do not dispense/initiate propranolol without assessing the clinical significance of the bradycardia — verify heart rate, indication, formulation, and concomitant medicines • if already prescribed, contact the prescriber for clinical review rather than independently discontinuing therapy",
    "High — regulatory labeling plus established pharmacology",
    "The C1 designation should track what the specific product labeling actually contraindicates, factoring in formulation and how clinically significant the bradycardia is — don't flag every mildly low heart rate as an automatic contraindication.",
    "drug-disease"),

  mk("PS-DIS-PROP-ASTHMA-001","Propranolol","Asthma","Drug–Disease Interaction","critical",true,
    "Bronchospasm / worsening of asthma",
    "Propranolol is a non-selective beta-blocker; blocking β2 receptors in the airways can cause bronchoconstriction and may precipitate or worsen bronchospasm in patients with asthma, where labeling identifies this as a contraindication.",
    "Blocks β2-adrenergic receptors in bronchial smooth muscle, reducing normal β2-mediated bronchodilation and increasing airway resistance. Because propranolol is non-selective, this pulmonary effect is clinically important in asthma.",
    "Bronchospasm, wheezing, dyspnea, increased airway resistance, acute worsening of asthma symptoms, and potentially severe respiratory compromise in susceptible patients. Beta-blockade can also blunt the response to β2-agonist rescue treatment.",
    "Respiratory symptoms • wheezing • dyspnea • bronchospasm • respiratory status • response to prescribed bronchodilator therapy",
    "Do not routinely dispense/initiate propranolol where labeling identifies asthma as a contraindication — verify asthma severity/current status, the propranolol formulation and indication, and whether a safer alternative exists • if already prescribed, contact the prescriber rather than stopping therapy independently",
    "High — regulatory labeling plus established pharmacology",
    "Don't generalize this to every beta-blocker or every respiratory condition — cardioselective agents and mild, well-controlled disease can change the picture; the C1 designation should reflect the specific labeling and clinical context.",
    "drug-disease"),

  // ---------------- NEW CATEGORY: DRUG–LABORATORY TEST (1) ----------------
  mk("PS-LAB-CRO-GLU-001","Ceftriaxone","Urinary glucose test (copper-reduction method — e.g. Benedict's/Fehling's solution)","Drug–Laboratory Test Interaction","minor",false,
    "Possible false-positive urinary glucose result",
    "Ceftriaxone can interfere with copper-reduction methods used to test urinary glucose (e.g. Benedict's or Fehling's solution), potentially producing a false-positive glucosuria result — this is an analytical interference, not true hyperglycemia.",
    "Copper-reduction tests detect reducing substances by converting cupric ions (Cu2+) to cuprous ions (Cu+). Ceftriaxone can interfere with this reaction, producing a false positive colorimetric result.",
    "A false-positive result may lead to incorrect interpretation of glucosuria, unnecessary investigation for diabetes/hyperglycemia, and unnecessary repeat testing.",
    "Determine which analytical method is being used • confirm whether it's a copper-reduction method • inform the lab that the patient is on ceftriaxone • prefer a glucose-specific enzymatic method where appropriate • interpret results alongside blood glucose and the overall picture",
    "Check the lab method before interpreting an unexpected positive urinary glucose result • don't assume a positive copper-reduction test is true glucosuria without clinical correlation",
    "Regulatory/product labeling describes this specific analytical interference",
    "This is a lab-method artifact, not a pharmacological effect — don't generalize it to enzymatic glucose-specific assays, which aren't affected the same way.",
    "drug-lab"),

  // ---------------- NEW CATEGORY: DRUG–FOOD (4 — one per fluoroquinolone, matching the per-drug approach used elsewhere) ----------------
  mk("PS-FOOD-CIP-CATION-001","Ciprofloxacin","Cation-rich foods & beverages (calcium, magnesium, aluminum, iron)","Drug–Food Interaction","moderate",false,
    "↓ oral absorption / ↓ systemic exposure",
    "Ciprofloxacin can bind polyvalent metal cations in the gut, forming poorly absorbed complexes and reducing how much antibiotic actually gets into the bloodstream when taken orally.",
    "Chelation/complex formation between the fluoroquinolone and cations like calcium, magnesium, aluminum or iron in the GI tract, reducing oral bioavailability.",
    "Lower-than-intended antibiotic exposure, reduced therapeutic effectiveness, persistence or worsening of infection, potential treatment failure, and a contribution to antimicrobial resistance if exposure is inadequate. Relevant mainly for oral dosing, much less so for IV.",
    "Confirm oral vs IV administration • ask about calcium/magnesium/iron supplements, antacids, multivitamins, and dairy timing • check product labeling for the required separation interval",
    "Separate administration from cation-containing products per the specific product's labeling • counsel the patient not to take antacids/mineral supplements/dairy at the same time as an oral dose unless instructed",
    "Regulatory labeling and pharmacokinetic studies support this for oral fluoroquinolones and polyvalent cations",
    "Don't apply one blanket separation rule to every fluoroquinolone or every cation source — check the specific product labeling, and remember IV administration isn't affected the same way.",
    "drug-food"),

  mk("PS-FOOD-LEV-CATION-001","Levofloxacin","Cation-rich foods & beverages (calcium, magnesium, aluminum, iron)","Drug–Food Interaction","moderate",false,
    "↓ oral absorption / ↓ systemic exposure",
    "Levofloxacin can bind polyvalent metal cations in the gut, forming poorly absorbed complexes and reducing oral antibiotic exposure.",
    "Chelation/complex formation with cations like calcium, magnesium, aluminum or iron in the GI tract, reducing oral bioavailability.",
    "Lower-than-intended antibiotic exposure, reduced effectiveness, persistence of infection, potential treatment failure. Relevant mainly for oral dosing.",
    "Confirm oral vs IV administration • ask about calcium/magnesium/iron supplements, antacids, multivitamins, and dairy timing • check product labeling for the required separation interval",
    "Separate administration from cation-containing products per labeling • counsel the patient accordingly",
    "Regulatory labeling and pharmacokinetic studies support this for oral fluoroquinolones and polyvalent cations",
    "Don't apply one blanket separation rule to every fluoroquinolone — check the specific product labeling.",
    "drug-food"),

  mk("PS-FOOD-MOX-CATION-001","Moxifloxacin","Cation-rich foods & beverages (calcium, magnesium, aluminum, iron)","Drug–Food Interaction","moderate",false,
    "↓ oral absorption / ↓ systemic exposure",
    "Moxifloxacin can bind polyvalent metal cations in the gut, forming poorly absorbed complexes and reducing oral antibiotic exposure.",
    "Chelation/complex formation with cations like calcium, magnesium, aluminum or iron in the GI tract, reducing oral bioavailability.",
    "Lower-than-intended antibiotic exposure, reduced effectiveness, persistence of infection, potential treatment failure. Relevant mainly for oral dosing.",
    "Confirm oral vs IV administration • ask about calcium/magnesium/iron supplements, antacids, multivitamins, and dairy timing • check product labeling for the required separation interval",
    "Separate administration from cation-containing products per labeling • counsel the patient accordingly",
    "Regulatory labeling and pharmacokinetic studies support this for oral fluoroquinolones and polyvalent cations",
    "Don't apply one blanket separation rule to every fluoroquinolone — check the specific product labeling.",
    "drug-food"),

  mk("PS-FOOD-OFL-CATION-001","Ofloxacin","Cation-rich foods & beverages (calcium, magnesium, aluminum, iron)","Drug–Food Interaction","moderate",false,
    "↓ oral absorption / ↓ systemic exposure",
    "Ofloxacin can bind polyvalent metal cations in the gut, forming poorly absorbed complexes and reducing oral antibiotic exposure.",
    "Chelation/complex formation with cations like calcium, magnesium, aluminum or iron in the GI tract, reducing oral bioavailability.",
    "Lower-than-intended antibiotic exposure, reduced effectiveness, persistence of infection, potential treatment failure. Relevant mainly for oral dosing.",
    "Confirm oral vs IV administration • ask about calcium/magnesium/iron supplements, antacids, multivitamins, and dairy timing • check product labeling for the required separation interval",
    "Separate administration from cation-containing products per labeling • counsel the patient accordingly",
    "Regulatory labeling and pharmacokinetic studies support this for oral fluoroquinolones and polyvalent cations",
    "Don't apply one blanket separation rule to every fluoroquinolone — check the specific product labeling.",
    "drug-food"),

  // ---------------- NEW CATEGORY: DRUG–DRINK — grapefruit juice (4) ----------------
  mk("PS-DRINK-GRAPEFRUIT-CBZ-001","Carbamazepine","Grapefruit juice","Drug–Drink Interaction","major",false,
    "↑ carbamazepine exposure",
    "Grapefruit juice inhibits intestinal CYP3A4, which can increase carbamazepine exposure and the risk of concentration-related adverse effects. Current labeling lists grapefruit juice among agents that may raise carbamazepine levels.",
    "CYP3A4 inhibition reduces carbamazepine metabolism, increasing plasma concentration.",
    "Dizziness, drowsiness, ataxia, diplopia, nausea/vomiting, and other concentration-related adverse effects.",
    "Watch for dizziness, drowsiness, ataxia, diplopia or nausea • carbamazepine level if toxicity is suspected",
    "Advise avoiding routine grapefruit/grapefruit juice during carbamazepine therapy unless specifically assessed • monitor for adverse effects if exposure occurs",
    "Regulatory labeling",
    null,
    "drug-drink"),

  mk("PS-DRINK-GRAPEFRUIT-NIF-001","Nifedipine","Grapefruit juice","Drug–Drink Interaction","major",false,
    "↑ nifedipine exposure (~2x AUC/Cmax reported)",
    "Grapefruit juice inhibits CYP3A4-mediated first-pass metabolism of nifedipine, increasing systemic exposure. Labeling reports roughly a two-fold increase in AUC and Cmax with repeated grapefruit juice exposure and recommends avoiding it.",
    "CYP3A4 inhibition reduces first-pass metabolism, increasing nifedipine blood levels.",
    "Excessive vasodilation, hypotension, dizziness, flushing, headache, tachycardia, and other dose-related effects.",
    "Blood pressure • symptoms of excessive hypotension (dizziness, flushing, headache, tachycardia)",
    "Advise patients to avoid grapefruit and grapefruit juice entirely while on nifedipine • monitor blood pressure when clinically appropriate",
    "Regulatory labeling — approximately 2x AUC/Cmax increase reported",
    null,
    "drug-drink"),

  mk("PS-DRINK-GRAPEFRUIT-MDZ-001","Midazolam","Grapefruit juice","Drug–Drink Interaction","major",false,
    "↑ oral midazolam exposure (Cmax +56%, AUC +52% reported)",
    "Grapefruit juice inhibits CYP3A4-mediated metabolism of oral midazolam, increasing exposure. Labeling specifically states oral midazolam should not be taken with grapefruit juice.",
    "CYP3A4 inhibition reduces first-pass metabolism of oral midazolam specifically — intestinal CYP3A4 contributes substantially to its first-pass effect.",
    "Excessive or prolonged sedation, psychomotor impairment, amnesia, and respiratory depression, particularly with other CNS depressants on board.",
    "Level of sedation • respiratory status • other concurrent CNS depressants",
    "Avoid grapefruit juice with oral midazolam entirely • review other CNS depressants and monitor for excessive/prolonged sedation",
    "Regulatory labeling — 200 mL grapefruit juice increased oral midazolam Cmax by ~56% and AUC by ~52% in PK data",
    "Route matters: this is specific to oral midazolam, not necessarily every route of administration.",
    "drug-drink"),

  mk("PS-DRINK-GRAPEFRUIT-CSA-001","Cyclosporine","Grapefruit juice","Drug–Drink Interaction","major",false,
    "↑ cyclosporine exposure",
    "Grapefruit and grapefruit juice can raise cyclosporine blood concentrations by affecting its metabolism and/or intestinal drug-handling. Labeling states grapefruit/grapefruit juice increase cyclosporine concentrations and should be avoided.",
    "Inhibition of intestinal CYP3A4 and effects on drug transport reduce presystemic clearance, increasing cyclosporine exposure.",
    "Increased risk of concentration-related toxicity: nephrotoxicity, hypertension, neurotoxicity, tremor, and other cyclosporine-related adverse effects — cyclosporine has a narrow therapeutic range, so this matters clinically.",
    "Cyclosporine concentration per protocol • renal function • blood pressure • signs of toxicity • consistency of dietary habits around grapefruit",
    "Advise patients to avoid grapefruit and grapefruit juice entirely • monitor levels, renal function and blood pressure per protocol",
    "Regulatory labeling",
    "C1/Contraindicated should NOT be used just because avoidance is advised — this is correctly a C2/Major with a clear 'avoid' action, not a full contraindication.",
    "drug-drink"),

  // ================================================================
  // AI-SUPPLEMENTED RECORDS (source: "ai-supplemented")
  // Added by Claude to broaden drug-class coverage, using well-established
  // pharmacology and regulatory labeling. These are flagged separately from
  // the project document's curated records and marked "pending review" in
  // the UI until a pharmacist has checked them — same honesty standard as
  // the rest of the dataset: nothing here is invented or uncertain, but it
  // has not yet been through the same human review as the original 66.
  // ================================================================

  mk("AI-SIL-NITRO-001","Sildenafil","Nitrates (e.g. nitroglycerin, isosorbide)","Pharmacodynamic — additive vasodilation","critical",true,
    "Severe, potentially life-threatening hypotension",
    "Both drugs increase cGMP-mediated vasodilation through the same pathway; combined use can cause a profound, sudden drop in blood pressure.",
    "Sildenafil inhibits PDE5, preventing breakdown of cGMP; nitrates release nitric oxide, which raises cGMP — together the effect on vascular smooth muscle is additive rather than the drugs simply adding two mild effects.",
    "Severe hypotension, syncope, and reports of myocardial infarction and death associated with this combination.",
    "Do not administer — if a patient on nitrates presents needing sildenafil (or vice versa), refer back to the prescriber rather than dispensing",
    "This is a hold-and-refer situation, not a monitor-and-continue one • ask specifically about nitrate use (including PRN sublingual nitroglycerin) before dispensing any PDE5 inhibitor",
    "High — regulatory labeling explicitly contraindicates this combination",
    "Applies to all PDE5 inhibitors (sildenafil, tadalafil, vardenafil), not just sildenafil specifically.",
    "drug-drug","ai-supplemented"),

  mk("AI-SER-MAOI-001","Sertraline","MAOIs (e.g. phenelzine, selegiline, linezolid)","Pharmacodynamic — serotonin syndrome risk","critical",true,
    "Serotonin syndrome — potentially fatal",
    "Combining an SSRI with a monoamine oxidase inhibitor can cause dangerous serotonin accumulation.",
    "Sertraline blocks serotonin reuptake while MAOIs block serotonin breakdown — together, synaptic serotonin can rise to dangerous levels.",
    "Serotonin syndrome: agitation, hyperthermia, tremor, rigidity, autonomic instability, and in severe cases seizures or death.",
    "Do not initiate together • a washout period is required when switching between an SSRI and an MAOI (commonly at least 14 days, longer for fluoxetine specifically — verify the exact interval for the specific SSRI)",
    "Confirm no MAOI use, including linezolid (an antibiotic with MAOI activity) and methylene blue, before dispensing any SSRI • this is a hold-and-refer situation",
    "High — regulatory labeling explicitly contraindicates this combination",
    "Linezolid and IV methylene blue are the two most commonly missed 'hidden' MAOIs — always ask about recent antibiotic use.",
    "drug-drug","ai-supplemented"),

  mk("AI-LIS-SPIRO-001","Lisinopril","Spironolactone","Pharmacodynamic — additive hyperkalemia risk","major",false,
    "↑ risk of dangerous hyperkalemia",
    "Combining an ACE inhibitor with a potassium-sparing diuretic can raise potassium to dangerous levels, particularly with renal impairment.",
    "Lisinopril reduces aldosterone-driven potassium excretion; spironolactone directly blocks the aldosterone receptor — both reduce renal potassium loss through different mechanisms.",
    "Hyperkalemia, which can cause dangerous cardiac arrhythmias; risk rises further with renal impairment, diabetes, or other potassium-raising drugs.",
    "Serum potassium and renal function at baseline, after starting, and periodically thereafter • ECG if potassium is significantly elevated",
    "This combination is sometimes used deliberately (e.g. in heart failure) under monitoring — verify a potassium-monitoring plan is actually in place, don't assume it's routinely wrong",
    "High — well-established, seen in heart-failure guideline-directed therapy with specific monitoring requirements",
    null,
    "drug-drug","ai-supplemented"),

  mk("AI-DIG-VERAP-001","Digoxin","Verapamil","Pharmacokinetic — P-gp inhibition","major",false,
    "↑ digoxin concentration, ↑ toxicity risk",
    "Verapamil inhibits P-glycoprotein-mediated digoxin clearance and can raise digoxin levels substantially, sometimes combined with additive cardiac conduction effects.",
    "P-gp inhibition reduces digoxin renal and biliary clearance; verapamil also has its own AV-nodal blocking effect, which can compound digoxin's effect on heart rate.",
    "Digoxin toxicity (nausea, visual disturbance, arrhythmias) and/or excessive bradycardia/AV block from the combined conduction effects.",
    "Digoxin level • heart rate • ECG • renal function • symptoms of digoxin toxicity",
    "A digoxin dose reduction is often needed when verapamil is started — confirm this has been addressed, don't assume the current dose still applies",
    "High — well-established pharmacokinetic interaction, reflected in verapamil and digoxin labeling",
    null,
    "drug-drug","ai-supplemented"),

  mk("AI-LITH-IBU-001","Lithium","NSAIDs (e.g. ibuprofen, naproxen)","Pharmacokinetic — reduced renal clearance","major",false,
    "↑ lithium concentration, ↑ toxicity risk",
    "NSAIDs can reduce renal lithium clearance and raise lithium levels into a toxic range — lithium has a narrow therapeutic index, so this matters even with short NSAID courses.",
    "NSAIDs inhibit renal prostaglandin synthesis, reducing renal blood flow and lithium excretion.",
    "Lithium toxicity: tremor, confusion, ataxia, and in severe cases seizures, arrhythmias, and renal failure.",
    "Lithium level, renal function, and clinical toxicity symptoms if NSAID use is more than occasional",
    "Prefer acetaminophen for pain relief where clinically appropriate • if NSAID use is necessary, involve the prescriber for a monitoring plan rather than treating it as routine OTC use",
    "High — well-established, applies across the NSAID class (aspirin at low antiplatelet doses is a partial exception)",
    null,
    "drug-drug","ai-supplemented"),

  mk("AI-MET-CONTRAST-001","Metformin","Iodinated contrast media","Pharmacokinetic/toxicodynamic — lactic acidosis risk","major","conditional",
    "↑ risk of lactic acidosis if renal function drops after contrast",
    "Iodinated contrast can transiently reduce renal function; if metformin isn't held around the time of contrast administration in at-risk patients, reduced clearance can raise the risk of lactic acidosis.",
    "Contrast-induced nephropathy reduces renal metformin clearance; metformin accumulation increases lactate production, and impaired renal clearance of that lactate compounds the risk.",
    "Lactic acidosis is rare but serious: malaise, GI symptoms, hyperventilation, and in severe cases hemodynamic instability.",
    "Renal function before and after the contrast study, per current institutional/radiology protocol",
    "Verify local protocol — current guidance for patients with normal renal function often does not require holding metformin, while those with reduced eGFR or receiving intra-arterial contrast usually do • don't apply a single blanket rule without checking eGFR",
    "High — well-established, though specific hold/resume protocols vary by institution and current renal function",
    "The historical 'always hold metformin 48 hours around any contrast' rule has been relaxed in current guidelines for patients with normal renal function — verify against current institutional protocol rather than an old fixed rule.",
    "drug-drug","ai-supplemented"),

  mk("AI-MTX-IBU-001","Methotrexate","NSAIDs (e.g. ibuprofen, naproxen)","Pharmacokinetic — reduced renal clearance","major","conditional",
    "↑ methotrexate exposure, ↑ toxicity risk",
    "NSAIDs can reduce renal methotrexate clearance, particularly relevant at higher (e.g. oncologic) methotrexate doses, raising the risk of serious toxicity.",
    "Renal prostaglandin inhibition reduces methotrexate clearance; NSAIDs may also displace methotrexate from plasma protein binding.",
    "Myelosuppression, mucositis, hepatotoxicity, and renal impairment — risk is dose- and context-dependent.",
    "CBC, renal function, and methotrexate level (where applicable) with any concurrent NSAID use",
    "Low-dose weekly methotrexate (e.g. for rheumatoid arthritis) with occasional NSAID use is common in practice, but this still warrants monitoring rather than being treated as risk-free • high-dose methotrexate regimens require much stricter avoidance",
    "High — well-established, magnitude depends heavily on the methotrexate dose/indication",
    "Don't apply the same level of concern to low-dose weekly rheumatologic methotrexate as to high-dose oncologic methotrexate — the risk profile is meaningfully different.",
    "drug-drug","ai-supplemented"),

  mk("AI-ALLO-AZA-001","Allopurinol","Azathioprine","Pharmacokinetic — xanthine oxidase inhibition","major",false,
    "↑ azathioprine/6-mercaptopurine exposure, ↑ toxicity risk",
    "Allopurinol inhibits the enzyme that normally inactivates azathioprine's active metabolite, and can cause severe, potentially life-threatening myelosuppression if the azathioprine dose isn't reduced.",
    "Xanthine oxidase normally breaks down 6-mercaptopurine (azathioprine's active metabolite); allopurinol strongly inhibits this enzyme, raising 6-MP exposure substantially.",
    "Severe myelosuppression (leukopenia, thrombocytopenia), increasing infection and bleeding risk.",
    "CBC closely after starting the combination and with any dose change",
    "Azathioprine dose typically needs to be reduced substantially (often to about 25% of the original dose) when allopurinol is started — confirm this adjustment has actually been made, don't assume the prescriber caught it",
    "High — well-established, explicitly addressed in both drugs' labeling",
    null,
    "drug-drug","ai-supplemented"),

  mk("AI-INSUL-PROP-001","Insulin","Propranolol","Pharmacodynamic — masked hypoglycemia symptoms","moderate",false,
    "Masked warning signs of hypoglycemia; possible prolonged hypoglycemia",
    "Non-selective beta-blockers can blunt the adrenergic warning symptoms of hypoglycemia (tremor, palpitations), making low blood sugar harder for the patient to recognize, and may also delay glucose recovery.",
    "Beta-blockade suppresses the sympathetic response that normally produces early hypoglycemia warning symptoms, and can blunt some counter-regulatory glucose-raising mechanisms.",
    "Hypoglycemia may present with sweating (largely preserved, a cholinergic response) but without the usual tremor/palpitations — patients may not notice it as early, and recovery may take longer.",
    "Blood glucose monitoring frequency and awareness • counsel the patient that sweating may become the more reliable hypoglycemia warning sign while on a non-selective beta-blocker",
    "This doesn't mean avoid the combination — beta-blockers are frequently necessary in diabetic patients — but patient education about atypical hypoglycemia symptoms is important",
    "High — well-established pharmacology, reflected in beta-blocker labeling",
    "Cardioselective beta-blockers (e.g. metoprolol) have a smaller version of this effect than non-selective agents like propranolol — don't treat every beta-blocker identically.",
    "drug-drug","ai-supplemented"),

  mk("AI-CIPRO-THEO-001","Ciprofloxacin","Theophylline","Pharmacokinetic — CYP1A2 inhibition","major",false,
    "↑ theophylline concentration, ↑ toxicity risk",
    "Ciprofloxacin inhibits CYP1A2-mediated theophylline metabolism and can raise theophylline levels into a toxic range — theophylline has a narrow therapeutic index.",
    "CYP1A2 inhibition reduces theophylline clearance, increasing plasma concentration.",
    "Theophylline toxicity: nausea, tremor, tachycardia, and in severe cases seizures and life-threatening arrhythmias.",
    "Theophylline level, heart rate, and toxicity symptoms if the combination can't be avoided",
    "Consider a fluoroquinolone with less CYP1A2 interaction (or an entirely different antibiotic class) where clinically appropriate • if ciprofloxacin is necessary, involve the prescriber about theophylline dose adjustment and monitoring",
    "High — well-established, explicitly addressed in ciprofloxacin labeling",
    null,
    "drug-drug","ai-supplemented"),

  mk("AI-TRAM-SSRI-001","Tramadol","SSRIs (e.g. sertraline, fluoxetine)","Pharmacodynamic — serotonin syndrome risk","major",false,
    "↑ risk of serotonin syndrome",
    "Tramadol has serotonergic activity in addition to its opioid effect; combined with an SSRI, this can raise the risk of serotonin syndrome — a smaller-magnitude version of the SSRI+MAOI risk, but still clinically real.",
    "Tramadol inhibits serotonin (and norepinephrine) reuptake in addition to weak mu-opioid agonism; combined with an SSRI's serotonin reuptake inhibition, synaptic serotonin can rise excessively.",
    "Serotonin syndrome symptoms: agitation, tremor, hyperreflexia, sweating, and in severe cases hyperthermia and altered mental status. Also consider reduced seizure threshold with this combination.",
    "Watch for early serotonin syndrome symptoms, especially after starting or increasing either drug's dose",
    "This combination is common in practice and isn't automatically avoided — but it warrants patient counseling on symptoms to watch for, particularly in the first days of combined use",
    "Moderate-to-high — well-established mechanism, clinical severity is usually lower than the classic SSRI+MAOI combination",
    null,
    "drug-drug","ai-supplemented"),

  mk("AI-CLIND-WAR-001","Clindamycin","Warfarin","Pharmacodynamic/indirect — variable INR effect","moderate",false,
    "Possible ↑ INR, especially in unwell or poorly-eating patients",
    "Clindamycin, like several antibiotics, has been associated with enhanced warfarin effect and INR elevation, particularly through reduced gut vitamin-K-producing flora during acute illness.",
    "Antibiotic-related suppression of vitamin-K-producing gut flora, compounded by reduced oral intake during acute illness — a mechanism shared with several other antibiotics rather than a specific enzyme interaction.",
    "Elevated INR and increased bleeding risk, particularly in elderly or acutely unwell patients with poor oral intake.",
    "INR monitoring during and shortly after antibiotic therapy, especially in patients who are eating poorly or acutely unwell",
    "Any broad-spectrum antibiotic course in a warfarin patient warrants closer INR follow-up, not just the specific agents already in this dataset — this is a class-level caution as much as a drug-specific one",
    "Moderate — mechanistically plausible and reported, less extensively quantified than the stronger CYP-based warfarin interactions already in this dataset",
    null,
    "drug-drug","ai-supplemented"),

  // ================================================================
  // SECTION B ADDITIONS — Paracetamol group (5), from the friend's updated
  // document. These are curated (not AI-supplemented) since they came
  // directly from the project document.
  // ================================================================

  mk("PS-PARA-WAR-001","Paracetamol","Warfarin","Pharmacodynamic / coagulation-related","moderate",false,
    "↑ anticoagulant effect with regular/prolonged use",
    "Regular or prolonged paracetamol use can enhance warfarin's anticoagulant effect and raise INR and bleeding risk — occasional doses generally have little effect. Product information reports this is more likely with repeated doses, particularly around 1.5–2 g/day for 5–7+ days.",
    "Not completely established. Repeated paracetamol exposure may interfere with vitamin-K-dependent coagulation processes, potentiating warfarin's anticoagulant effect.",
    "Increased INR, easy bruising, epistaxis, GI bleeding, hematuria, and serious bleeding in susceptible patients.",
    "INR more closely with regular/prolonged paracetamol use • assess other bleeding-risk medicines and patient risk factors",
    "Occasional/short-term paracetamol use generally does not require the same level of concern • counsel the patient to report unusual bleeding or bruising • avoid repeated/high doses without informing whoever manages their warfarin therapy",
    "Product information supports enhancement of warfarin's anticoagulant effect with prolonged regular paracetamol use",
    "Clinically significant mainly with regular/prolonged use, not occasional dosing — don't flag a single dose the same way as a multi-day course."),

  mk("PS-PARA-RIF-001","Paracetamol","Rifampicin","Pharmacokinetic / hepatotoxicity-related","major",false,
    "↑ risk of hepatotoxicity",
    "Rifampicin is a potent hepatic enzyme inducer, and product information specifically warns that concomitant paracetamol may increase the risk of hepatotoxicity, particularly with repeated/high-dose paracetamol or other hepatic risk factors.",
    "Rifampicin induces hepatic drug-metabolizing pathways involved in paracetamol metabolism, which can alter paracetamol exposure and may increase formation of hepatotoxic metabolites, particularly at high or repeated doses.",
    "Increased hepatic enzyme elevations, drug-induced liver injury, hepatocellular injury, hepatitis, and rarely acute liver failure — particularly important with liver disease, malnutrition, chronic alcohol use, or other hepatotoxic medicines.",
    "Liver function when clinically indicated, especially in high-risk patients • review total daily paracetamol exposure from all combination products",
    "Avoid unnecessary prolonged/high-dose paracetamol during rifampicin treatment • consider hepatic risk factors • counsel on jaundice, dark urine, persistent nausea/vomiting, unusual fatigue, or right-upper-abdominal pain",
    "Direct product-information warning supports increased hepatotoxicity risk with concomitant use"),

  mk("PS-PARA-ETOH-001","Paracetamol","Alcohol/Ethanol","Pharmacodynamic / toxicological","major",false,
    "↑ risk of paracetamol-associated liver injury",
    "Alcohol can increase the risk of paracetamol-associated liver injury, particularly with excessive/chronic alcohol consumption, high or repeated paracetamol doses, malnutrition, or glutathione depletion. Risk depends strongly on the pattern and amount of alcohol use, not just the fact that both are present.",
    "Paracetamol is partly metabolized to the reactive metabolite NAPQI, normally detoxified by glutathione. Excessive alcohol use and associated nutritional/glutathione depletion can increase susceptibility to hepatic injury.",
    "Elevated liver enzymes, hepatocellular injury, acute hepatitis, and hepatic failure in severe toxicity.",
    "Assess alcohol consumption before recommending repeated/high-dose paracetamol • use additional caution in chronic alcohol misuse, liver disease, malnutrition, or prolonged therapy",
    "Advise avoiding excessive alcohol while using paracetamol, and not exceeding the recommended dose • ensure the patient isn't also taking another paracetamol-containing product • seek urgent medical advice after suspected overdose, even if the patient initially feels well",
    "Regulatory/clinical toxicology basis for NAPQI/glutathione mechanism",
    "Do NOT automatically label this contraindicated for every patient who drinks any alcohol — the risk depends on exposure pattern and patient-specific factors, per the source document's explicit guidance."),

  mk("PS-PARA-VALP-001","Paracetamol","Valproic Acid","Pharmacodynamic (hepatotoxicity concern) — not an established PK interaction","moderate",false,
    "Possible additive hepatotoxicity concern, not a proven major interaction",
    "Both paracetamol and valproic acid can cause drug-induced liver injury, so concomitant use may raise concern for hepatic toxicity in patients with additional hepatic risk factors — but this should not be presented as a proven major interaction.",
    "The principal concern is potentially additive hepatic toxicity, rather than a clearly established alteration in paracetamol pharmacokinetics. Valproic acid labeling reports valproate had no effect on acetaminophen's pharmacokinetic parameters in a small 3-patient study.",
    "Increased ALT/AST, hepatic dysfunction, hepatocellular injury, and rare severe liver injury — risk is greater with existing hepatic impairment or other hepatotoxic exposures.",
    "Liver-function monitoring when clinically warranted • review hepatic history and concurrent hepatotoxic medicines",
    "Avoid unnecessary prolonged/high-dose paracetamol • do not automatically classify this pair as contraindicated • counsel on jaundice, dark urine, persistent vomiting, severe fatigue, or abdominal pain",
    "Direct pharmacokinetic evidence does not demonstrate a meaningful PK interaction — the hepatic-toxicity concern is principally a clinical/pharmacodynamic safety consideration",
    "The source document is explicit that this is not established as a major pharmacokinetic interaction — keep the severity proportionate to that uncertainty rather than escalating it."),

  mk("PS-PARA-PROB-001","Paracetamol","Probenecid","Pharmacokinetic","moderate",false,
    "↑ paracetamol exposure — dose adjustment may be needed",
    "Probenecid inhibits paracetamol glucuronidation and can approximately halve paracetamol clearance, potentially increasing exposure. Product information recommends dose reduction when used together.",
    "Probenecid → inhibition of paracetamol glucuronidation → reduced clearance → increased paracetamol exposure.",
    "Increased risk of dose-related adverse effects, hepatotoxicity (particularly with high/repeated doses), and accumulation during prolonged treatment.",
    "Review the paracetamol dose when probenecid is initiated or already in use • assess additional hepatic risk factors",
    "Consider a lower paracetamol dose where appropriate • avoid unnecessary prolonged/high-dose therapy • advise not increasing the paracetamol dose without medical advice, and checking combination products to avoid accidental excess",
    "Product information states probenecid nearly halves paracetamol clearance by inhibiting glucuronidation and that the paracetamol dose may need to be reduced"),
];

// Drugs that should be treated as members of a shared interaction class
// (i.e. they don't have their own record, they inherit the class record).
// Reserved for future drug-class groupings (none needed currently — every
// drug, including each individual fluoroquinolone, now has its own record).
const CLASS_ALIASES = {};

// Build a full index of every searchable "item" (medicine, condition, food,
// drink or lab test) with what KIND it is, so the frontend can tag chips
// correctly (e.g. "Asthma" shows as a condition, not a medicine).
const KIND_KEYWORDS = {
  "drug-drug": "medicine",
  "drug-disease": "condition",
  "drug-food": "food",
  "drug-drink": "drink",
  "drug-lab": "lab test",
};

function buildItemIndex() {
  const index = {}; // name -> kind label
  INTERACTIONS.forEach(i => {
    if (!(i.drugA in index)) index[i.drugA] = "medicine"; // drugA is always the actual drug
    const bKind = KIND_KEYWORDS[i.kind] || "medicine";
    if (!(i.drugB in index)) index[i.drugB] = bKind;
  });
  return index;
}

const ITEM_KINDS = buildItemIndex();
const DRUG_LIST = Object.keys(ITEM_KINDS).sort((a, b) => a.localeCompare(b));

// Node/Express reads this same file directly — one dataset, no duplication.
if (typeof module !== "undefined" && module.exports) {
  module.exports = { INTERACTIONS, DRUG_LIST, CLASS_ALIASES, ITEM_KINDS };
}
